Added ability for NGINX to use seedfile in OpenShift
We can now extract and use the seedfile provided as a source of
certificates for NGINX.

diff --git a/e2e/openshift/nginx/root/usr/bin/run-nginx b/e2e/openshift/nginx/root/usr/bin/run-nginx
--- a/e2e/openshift/nginx/root/usr/bin/run-nginx
+++ b/e2e/openshift/nginx/root/usr/bin/run-nginx
@@ -19,6 +19,29 @@ function generate_passwd_file() {
 
 generate_passwd_file
 
+if [ "$CONJUR_SEED_FILE" != "" ]; then
+  echo "Seed file setting detected. Extracting relevant info..."
+  if [ ! -f "$CONJUR_SEED_FILE" ]; then
+    echo "ERROR! Cannot find seed file '$CONJUR_SEED_FILE'!"
+    exit 1
+  fi
+
+  SOLO_PATH="/tmp/solo.json"
+  echo "Extracting solo.json and grabbing its values..."
+  seedfile-extractor "/etc/chef/solo.json" "$SOLO_PATH"
+
+  echo "Extracting seedfile certificates..."
+  hostname=$(jq -r '.conjur.hostname' "$SOLO_PATH")
+  seedfile-extractor "/opt/conjur/etc/ssl/ca.pem" "/opt/conjur/etc/ssl/ca/tls.crt"
+  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.pem" "/opt/conjur/etc/ssl/cert/tls.crt"
+  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.key" "/opt/conjur/etc/ssl/cert/tls.key"
+
+  # fix permissions on the private key
+  chmod 600 "/opt/conjur/etc/ssl/cert/tls.key"
+
+  echo "Seedfile data extracted!"
+fi
+
 echo "Verifying that all certs are in place..."
 all_certs_available="false"
 
