Made OpenShift Conjur container be able to unpack seedfiles
This should set the container up to be able to connect to the database
if the database allows the connections from that cert's user.

diff --git a/e2e/openshift/conjur/root/usr/bin/run-conjur b/e2e/openshift/conjur/root/usr/bin/run-conjur
--- a/e2e/openshift/conjur/root/usr/bin/run-conjur
+++ b/e2e/openshift/conjur/root/usr/bin/run-conjur
@@ -1,45 +1,57 @@
 #!/bin/bash -e
 
-PG_SOCKET=/var/run/postgresql/.s.PGSQL.5432
 PG_PORT=5432
-DATA_KEY_PATH="/opt/conjur/etc/conjur_data_key/conjur_data_key.txt"
-
 SLEEP_TIME=1
 
-# while [ ! -e "${PG_SOCKET}" ]; do
-while ! nc -z -v -w1 localhost "$PG_PORT" >/dev/null; do
-  echo "PG socket not found yet. Waiting $SLEEP_TIME seconds..."
-  sleep $SLEEP_TIME
-done
-echo "PG socket found. Continuing..."
-
-while [ ! -e "$DATA_KEY_PATH" ]; do
-  echo "Data key not found yet. Waiting $SLEEP_TIME seconds..."
-  sleep $SLEEP_TIME
-done
-echo "Data key found. Continuing..."
-export CONJUR_DATA_KEY="$(cat $DATA_KEY_PATH)"
-
-# Generate passwd file based on current uid
-function generate_passwd_file() {
-  export USER_ID=$(id -u)
-  export GROUP_ID=$(id -g)
-  grep -v ^conjur /etc/passwd > "$HOME/passwd"
-  echo "conjur:x:${USER_ID}:${GROUP_ID}:Conjur runner:${HOME}:/bin/bash" >> "$HOME/passwd"
-  export LD_PRELOAD=libnss_wrapper.so
-  export NSS_WRAPPER_PASSWD=${HOME}/passwd
-  export NSS_WRAPPER_GROUP=/etc/group
-}
-generate_passwd_file
-
 if [ "$DATABASE_URL" == "" ]; then
-  echo "DATABASE_URL not specified. Setting localhost:$PG_PORT as the value."
-  export DATABASE_URL="postgresql://conjur:conjur@localhost:$PG_PORT"
+  echo "ERROR: DATABASE_URL not specified!"
+  exit 1
 fi
+
+if [ "$CONJUR_SEED_FILE" != "" ]; then
+  echo "Seed file setting detected. Extracting relevant info..."
+  if [ ! -f "$CONJUR_SEED_FILE" ]; then
+    echo "ERROR! Cannot find seed file '$CONJUR_SEED_FILE'!"
+    exit 1
+  fi
+
+  SOLO_PATH="/tmp/solo.json"
+  echo "Extracting solo.json and grabbing its values..."
+  seedfile-extractor "/etc/chef/solo.json" "$SOLO_PATH"
+
+  echo "Extracting seedfile certificates..."
+  hostname=$(jq -r '.conjur.hostname' "$SOLO_PATH")
+  seedfile-extractor "/opt/conjur/etc/ssl/ca.pem" "/opt/conjur/etc/ssl/ca/tls.crt"
+  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.pem" "/opt/conjur/etc/ssl/cert/tls.crt"
+  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.key" "/opt/conjur/etc/ssl/cert/tls.key"
+
+
+  # fix permissions on the private key
+  chmod 600 "/opt/conjur/etc/ssl/cert/tls.key"
+
+  echo "Extracting CONJUR_DATA_KEY..."
+  seedfile-extractor "/opt/conjur/etc/possum.key" "/tmp/conjur_data_key"
+  export CONJUR_DATA_KEY=$(cat /tmp/conjur_data_key)
+  rm -rf /tmp/conjur_data_key
+
+  echo "Composing connection string..."
+
+  if [ "$CONJUR_DATABASE_HOSTNAME" == "" ]; then
+    echo "ERROR! CONJUR_DATABASE_HOSTNAME env var not defined!"
+    exit 1
+  fi
+
+  export DATABASE_URL="postgres://$hostname@$CONJUR_DATABASE_HOSTNAME:$PG_PORT/conjur?sslcert=/opt/conjur/etc/ssl/cert/tls.crt,sslkey=/opt/conjur/etc/ssl/cert/tls.key,sslmode=require"
+  echo "Using DATABASE_URL: '$DATABASE_URL'"
+
+  echo "Seedfile data extracted!"
+fi
+
+# TODO: Wait for PG to be up before continuing
 
 if [ "$DEBUG_CONTAINER" != "" ] && [ "$DEBUG_CONTAINER" != "false" ]; then
   echo "Container debugging activated... Waiting..."
   sleep 999d
 fi
 
-exec conjur-plugin-service possum
+exec conjurctl $@
