Added seedfile extraction to PG OpenShift container
We should be able to now replicate the database from master.

diff --git a/e2e/openshift/postgres/root/usr/bin/run-postgresql b/e2e/openshift/postgres/root/usr/bin/run-postgresql
--- a/e2e/openshift/postgres/root/usr/bin/run-postgresql
+++ b/e2e/openshift/postgres/root/usr/bin/run-postgresql
@@ -5,11 +5,40 @@ CLUSTER_NAME="main"
 PG_VERSION="9.4"
 INSTANCE="$version-$cluster"
 
+CONJUR_ROLE="follower"
+
 SSL_FILES=( "/opt/conjur/etc/ssl/ca/tls.crt"
             "/opt/conjur/etc/ssl/cert/tls.crt"
             "/opt/conjur/etc/ssl/cert/tls.key" )
 
 export PG_DATA="$HOME/$PG_VERSION/$CLUSTER_NAME"
+
+if [ "$CONJUR_SEED_FILE" != "" ]; then
+  echo "Seed file setting detected. Extracting relevant info..."
+  if [ ! -f "$CONJUR_SEED_FILE" ]; then
+    echo "ERROR! Cannot find seed file '$CONJUR_SEED_FILE'!"
+    exit 1
+  fi
+
+  SOLO_PATH="/tmp/solo.json"
+  echo "Extracting solo.json and grabbing its values..."
+  seedfile-extractor "/etc/chef/solo.json" "$SOLO_PATH"
+
+  export CONJUR_ACCOUNT=$(jq -r '.conjur.account' "$SOLO_PATH")
+  export CONJUR_MASTER_HOST=$(jq -r '.conjur.master_host' "$SOLO_PATH")
+  export CONJUR_ROLE=$(jq -r '.conjur.role' "$SOLO_PATH")
+
+  echo "Extracting seedfile certificates..."
+  hostname=$(jq -r '.conjur.hostname' "$SOLO_PATH")
+  seedfile-extractor "/opt/conjur/etc/ssl/ca.pem" "/opt/conjur/etc/ssl/ca/tls.crt"
+  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.pem" "/opt/conjur/etc/ssl/cert/tls.crt"
+  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.key" "/opt/conjur/etc/ssl/cert/tls.key"
+
+  # fix permissions on the private key
+  chmod 600 "/opt/conjur/etc/ssl/cert/tls.key"
+
+  echo "Seedfile data extracted!"
+fi
 
 # Sanity check
 if [ "$CONJUR_ACCOUNT" == "" ]; then
@@ -24,6 +53,7 @@ fi
 
 echo "Using master host: $CONJUR_MASTER_HOST"
 echo "Using account: $CONJUR_ACCOUNT"
+echo "Using role: $CONJUR_ROLE"
 
 # Generate passwd file based on current uid
 function generate_passwd_file() {
@@ -73,7 +103,7 @@ while [ "$all_certs_available" != "true" ]; do
 done
 
 echo "Doing a cluster initial base backup..."
-run-pg-basebackup "$CONJUR_ACCOUNT" "$CONJUR_MASTER_HOST" "follower"
+run-pg-basebackup "$CONJUR_ACCOUNT" "$CONJUR_MASTER_HOST" "$CONJUR_ROLE"
 
 # Overwrite fetched postgresql.conf and pg_hba since we want to use our own
 ln -fs /etc/postgresql/postgresql.conf "/etc/postgresql/$PG_VERSION/$CLUSTER_NAME/postgresql.conf"
